---

- name: Swift container cleanup
  hosts: all
  remote_user: root
  become: yes
  tasks:
    - name: Install xfsprogs package
      apt:
        name: xfsprogs
        state: present
        update_cache: yes
    - name: Copy script
      copy: src=../scripts/cleanup-swift.sh dest=/root/ mode=0777
    - name: Execute the script
      shell: /bin/bash /root/cleanup-swift.sh >> /root/out.cleanup.swift
      ignore_errors: yes
      become_user: root
