FROM conda_ubuntu
MAINTAINER lamtv10@viettel.com.vn
ENV DEBIAN_FRONTEND noninteractive
ENV SHARED_CONF_DIR /usr/share/dockerRUN apt-get -y update && apt-get -y dist-upgrade
#Clear cache apt
#RUN apt-get clean \
#    && rm -rf /var/lib/apt/lists/* \
#    && apt-get update -y

#RUN 	apt-get -y  install libgl1-mesa-glx libegl1-mesa libxrandr2 libxrandr2 libxss1 libxcursor1 libxcomposite1 libasound2 libxi6 libxtst6

#ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
#ENV PATH /opt/conda/bin:$PATH

#RUN apt-get update --fix-missing && \
#    apt-get install -y wget bzip2 ca-certificates libglib2.0-0 libxext6 libsm6 libxrender1 git mercurial subversion && \
#    apt-get clean

#RUN wget --quiet https://repo.anaconda.com/archive/Anaconda3-2019.10-Linux-x86_64.sh -O ~/anaconda.sh && \
 #   /bin/bash ~/anaconda.sh -b -p /opt/conda && \
 #   rm ~/anaconda.sh && \
 #   ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
 #   echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
 #   echo "conda activate base" >> ~/.bashrc && \
 #   find /opt/conda/ -follow -type f -name '*.a' -delete && \
 #   find /opt/conda/ -follow -type f -name '*.js.map' -delete && \
 #   /opt/conda/bin/conda clean -afy

#RUN conda install python=2.7
RUN conda install -c anaconda numpy
RUN conda install -c anaconda flask
RUN conda install -c anaconda pymysql
RUN conda install -c conda-forge flask-restplus
RUN conda install -c conda-forge ansible
RUN conda install -c anaconda configparser
RUN conda install -c anaconda sqlalchemy
RUN conda install -c conda-forge flask-sqlalchemy
RUN conda install -c conda-forge flask-migrate
RUN conda install -c anaconda flask-login
RUN conda install -c conda-forge pytest
RUN conda install -c conda-forge flask-wtf
RUN conda install -c conda-forge packaging
RUN conda install -c conda-forge fabric
RUN conda install -c anaconda redis
RUN conda install -c anaconda redis-py
RUN conda install PyYAML
RUN conda install pyOpenSSL
RUN conda install flake8
RUN conda install -c conda-forge flask-marshmallow
RUN conda install -c conda-forge marshmallow-sqlalchemy
RUN pip install ansible==2.7.4
RUN pip install Werkzeug==0.16.1



CMD [ "/bin/bash" ]

