- block:
  - name: 1.copy config
    debug: msg='Starting 1-------------------------------------------->'
  - include: extends/before.yml task_index=1
  - template:
      src: '{{ item.src }}'
      dest: '{{ item.dest }}'
      owner: root
      group: root
      mode: '0644'
      backup: yes
    with_items:
    - src: nova.conf.j2
      dest: /etc/nova/nova.conf
    - src: open.rc.j2
      dest: ~/open.rc
    - src: ceph.client.images.keyring.j2
      dest: /etc/ceph/ceph.client.images.keyring.j2
    - src: ceph.conf.j2
      dest: /etc/ceph/ceph.conf
    register: infos
  - include: extends/after_ok.yml task_index=1 info={{ infos  }}
  rescue:
  - include: extends/after_failse.yml task_index=1 info={{ infos  }}
  - fail: msg={{ infos  }}
  tags:
  - install
  - '1'
- block:
  - name: 2.systemctl enable openstack-nova-compute
    debug: msg='Starting 2-------------------------------------------->'
  - include: extends/before.yml task_index=2
  - systemd:
      name: openstack-nova-compute
      enabled: yes
      masked: no
    register: infos
  - include: extends/after_ok.yml task_index=2 info={{ infos  }}
  rescue:
  - include: extends/after_failse.yml task_index=2 info={{ infos  }}
  - fail: msg={{ infos  }}
  tags:
  - install
  - '2'
- block:
  - name: 3.restart libvirtd
    debug: msg='Starting 3-------------------------------------------->'
  - include: extends/before.yml task_index=3
  - systemd:
      state: restarted
      daemon_reload: yes
      name: libvirtd
    register: infos
  - include: extends/after_ok.yml task_index=3 info={{ infos  }}
  rescue:
  - include: extends/after_failse.yml task_index=3 info={{ infos  }}
  - fail: msg={{ infos  }}
  tags:
  - install
  - '3'
- block:
  - name: 4.start openstack-nova-compute
    debug: msg='Starting 4-------------------------------------------->'
  - include: extends/before.yml task_index=4
  - systemd:
      state: started
      daemon_reload: yes
      name: openstack-nova-compute
    register: infos
  - include: extends/after_ok.yml task_index=4 info={{ infos  }}
  rescue:
  - include: extends/after_failse.yml task_index=4 info={{ infos  }}
  - fail: msg={{ infos  }}
  tags:
  - install
  - '4'
