language: python
python:
  - "3.6"
  - "2.7"

addons:
  apt:
    packages:
      - openssh-server
      - software-properties-common

cache: pip

branches:
  only:
  - master
  - nginx

before_install:
    - sudo apt-add-repository --yes ppa:ansible/ansible
    - sudo apt-get update
    - sudo apt-get --yes install ansible

install:
  - pip install -r requirements.txt
  - python setup.py -q install
  - pip install coverage
  - pip install codecov

before_script:
  - cp -pr tests /tmp
  - cp ansible_runner_service.py /tmp

script:
  - flake8 --ignore=E501 ansible_runner_service.py runner-service/
  - cd /tmp/tests && python -m unittest discover -p "test_*.py"
  - coverage run -m unittest discover -p "test_*.py"

after_success:
  - codecov

after_script:
  - ls -al ~/.ssh
  - cat ~/.ssh/authorized_keys

# To trigger travis builds
