---
- name: install compute node 
  hosts: '{{target}}'
  vars_files:
    - /etc/ansible/group_vars/all/global.yml
    - /etc/ansible/group_vars/all/common.yml 
  remote_user: root 
  gather_facts: no 
  roles:
    - { role: test_ansible_command }
    - { role: swift_proxy }
