apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config
  namespace: kube-system
data:
  config.json: |
    {
        "resourceList": [{
                "resourceName": "intel_sriov_netdevice",
                "selectors": {
                    "vendors": ["8086"],
                    "devices": [ "10ed"],
                    "drivers": ["i40evf", "ixgbevf"],
                    "pfNames": ["ens2f0#2-7"]
                }
            }
        ]
    }
