---
group_name: Default

# Host Name và Host Ip của các Server
host_info:
  name:
    controller01: controller01
    controller02: controller02
    controller03: controller03
    compute01: compute01
    compute02: compute02

  ip:
    controller01: 172.16.30.60
    controller02: 172.16.31.248
    controller03: 172.16.31.247
    compute01: 172.16.31.247
    compute02: 172.16.30.60

# Ip Port của Docker Registry
repository: 172.16.30.89
port_docker_registry: 4000

# Tên các Docker Image dùng cài Openstack Service
docker_image:
  keystone: docker-registry:4000/keystone:q 
  glance: docker-registry:4000/glance:q
  nova: docker-registry:4000/nova:q  
  cinder_api: docker-registry:4000/cinder_api:q
  cinder_scheduler: docker-registry:4000/cinder_scheduler:q 
  cinder_volume: docker-registry:4000/cinder_volume_ceph_x:q
  neutron: docker-registry:4000/neutron:q 
  neutron_dpdk: docker-registry:4000/neutron:q 
  horizon: docker-registry:4000/horizon:q 
  swift_proxy: docker-registry:4000/swift_proxy_v6:q 
  neutron_agent: docker-registry:4000/neutron_dpdk:q

# Thư mục sẽ dùng để chứa các file cấu hình cho Openstack
usr_share_docker: /usr/share/docker

# Dùng để tự động lấy host_name
host_name: "{{ ansible_hostname }}"





